name             'ibm-power'
maintainer       'Oregon State University'
maintainer_email 'chef@osuosl.org'
source_url       'https://github.com/osuosl-cookbooks/ibm-power'
issues_url       'https://github.com/osuosl-cookbooks/ibm-power/issues'
license          'Apache-2.0'
chef_version     '>= 16.0'
description      'Installs/Configures ibm-power'
version          '3.0.0'

supports         'centos', '~> 7.0'
supports         'centos', '~> 8.0'
